apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-frontend
  template:
    metadata:
      labels:
        app: demo-frontend
    spec:
      containers:
      - name: demo-frontend
        image: sargishakobyan/demo-frontend:latest
        ports:
        - containerPort: 8080
