apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-backend
      tier: backend
  template:
    metadata:
      labels:
        app: demo-backend
        tier: backend
    spec:
      containers:
      - name: demo-backend
        image: sargishakobyan/demo-backend:latest
        ports:
        - containerPort: 8080
